#!/bin/bash

cd ~

# Brew
# #####################################

# Install homebrew; https://brew.sh/
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo >> ~/.zshenv
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshenv
source ~/.zshenv

# Fetch Brewfile
curl -o Brewfile https://raw.githubusercontent.com/notnotdrew/dots/refs/heads/main/Brewfile

# Install from Brewfile & cleanup
brew bundle && rm Brewfile

# Dock
# #####################################

# Automatically hide & show dock
defaults write com.apple.dock autohide -bool true

# Only show open apps in dock
defaults write com.apple.dock static-only -bool true

# Set tile size to minimum
defaults write com.apple.dock tilesize -int 16

# Restart dock
killall Dock

# Finder
# #####################################

# Show hidden files
defaults write com.apple.finder "AppleShowAllFiles" -bool "true" && killall Finder

# Music
# #####################################

# Don't show notifications for songs
defaults write com.apple.Music "userWantsPlaybackNotifications" -bool "false" && killall Music

# Todos
#
cat <<EOF
Opening preferences. The following should manually be updated:
  - Use caps lock as control: Keyboard > Keyboard Shortcuts > Modifier Keys
  - Use tap as click: Trackpad > Tap to click
EOF

open "x-apple.systempreferences:com.apple.preference.keyboard"
