#!/bin/bash

cd ~

# Brew & dotfiles
# #####################################

# Install homebrew; https://brew.sh/
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \
    echo >> ~/.zshenv && \
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshenv &&
    source ~/.zshenv

if [ ! -d "dots" ]; then
    git clone git@github.com:notnotdrew/dots.git
else
    echo "~/dots already exists, using as-is..."
fi

cd dots/ && \
    ./update_symlinks && \
    source ~/.zshenv && \
    brew bundle

sudo sh -c 'echo /opt/homebrew/bin/bash >> /etc/shells'
sudo sh -c 'echo /opt/homebrew/bin/zsh >> /etc/shells'
chsh -s /opt/homebrew/bin/zsh

# General config
# #####################################

# Show hidden files
defaults write com.apple.finder "AppleShowAllFiles" -bool "true" && killall Finder

# Don't show notifications for songs
defaults write com.apple.Music "userWantsPlaybackNotifications" -bool "false" && killall Music

# Automatically hide & show dock
defaults write com.apple.dock autohide -bool true

# Only show open apps in dock
defaults write com.apple.dock static-only -bool true

# Set tile size to minimum
defaults write com.apple.dock tilesize -int 16

# Restart dock
killall Dock

# Manual todos
# #####################################

cat <<EOF
TODO: The following should be updated manually in Preferences:
  - Change wallpaper: Wallpaper > Add Photo > ~/dots/wallpaper.gif
  - Use caps lock as control (for all keyboards): Keyboard > Keyboard Shortcuts > Modifier Keys
  - Use tap as click: Trackpad > Tap to click
EOF
