
export BREWSKIS=$HOME/Dropbox/development/brewskis
export DOWNLOADEMS=$HOME/Dropbox/development/downloadems
export DEVELOPMENT=$HOME/Documents/development
export NOTES=$HOME/Documents/development/notes
export GOPATH=$DEVELOPMENT/go-work
export CDPATH=$DEVELOPMENT
export PATH=$PATH:~/bin
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:$GOPATH/bin

export path="$path:$home/.rvm/bin" # add rvm to path for scripting

[[ -s "$home/.rvm/scripts/rvm" ]] && source "$home/.rvm/scripts/rvm" # load rvm into a shell session *as a function*

export NVM_DIR="/Users/drew/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export TERM=xterm-256color

export PATH="$HOME/.bin:~/bin:$PATH"

eval export
